name: test_snakemake
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - bioconda
  - defaults
  - r
  - singleronbio
dependencies:
  - mamba
  - bcftools==1.10
  - ca-certificates
  - certifi
  - openssl
  - snakemake=7.3.8
  - ensembl-vep==102
  - seqtk
  - rust-bio-tools
  - samtools
  - picard
