name: test_snakemake
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - bioconda
  - defaults
  - r
  - singleronbio
dependencies:
  - mamba
  - bcftools==1.12
  - ca-certificates
  - certifi
  - openssl
  - snakemake=7.3.8
  - ensembl-vep==102
  - seqtk
  - rust-bio-tools==0.38.2
  - samtools
  - picard==2.20.1
  - bwa==0.7.17
  - snakemake-wrapper-utils ==0.1.3
  - multiqc==1.10.1
  - gatk4==4.2.0.0
  - fastqc==0.11.9
  - trimmomatic==0.36