channels:
  - conda-forge
  - bioconda
  - defaults
  - r
  - singleronbio
dependencies:
  - ensembl-vep=102.0
  - numpy=1.21.6
  - pandas=1.3.5
  - perl=5.26.2
  - picard=2.27.3
  - pip=22.1.2
  - python=3.7.12
  - r-base=3.2.2
  - rust-bio-tools=0.38.2
  - samtools=1.6
  - seqtk=1.3
  - snakemake=7.3.8
  - pip:
    - altgraph==0.17.2
    - isal==0.11.1
    - pyinstaller-hooks-contrib==2022.7
    - pysam==0.19.1
    - tenacity==8.0.1
    - xopen==1.5.0
