rule plot_stats:
    input:
        calls="results/tables/calls.tsv.gz",
    output:
        depths=report(
            "results/plots/depths.svg", 
            caption="../report/depths.rst", 
            category="Plots"
        ),
        freqs=report(
            "results/plots/allele-freqs.svg",
            caption="../report/freqs.rst",
            category="Plots",
        ),
    log:
        "logs/plot-stats.log",
    benchmark:
        "results/benchmarks/plot-stats.benchmark.txt",
    script:
        "../../scripts/stats/plot_stats.py"